/**
 * Packet registry, keyed by filename and split by direction.
 *
 *   src/ops/c2s/GL_LOGIN_REQ.ts   the client sends it; we read it
 *   src/ops/s2c/GL_LOGIN_ACK.ts   we send it; we build it
 *
 * The opcode name appears in the filename and nowhere inside the module — a
 * builder receives its own opcode as the first argument, so nothing is
 * repeated and nothing can drift.
 *
 * Direction comes from the folder, not from the `_REQ`/`_ACK` suffix. Those
 * suffixes describe the *client's* view and do not always match ours:
 * `GT_PING_ACK` is an `_ACK` that the server sends, and `GT_PING_REQ` is a
 * `_REQ` that the server receives (docs/PACKETS.md §3.15pre).
 *
 * The two `index.ts` files are generated by `bun run sync` and checked for
 * staleness in the tests. They exist because ES modules have no glob import
 * and a dynamic `import(`./${name}.ts`)` degrades to `any`, which would put
 * opcode names and builder arguments back to failing at runtime.
 */

import { Glob } from "bun";
import type { Packet, Reader } from "../packet.ts";
import { opcodeFor, opcodeName } from "../opcodes.ts";
import type { Session } from "../session.ts";
import * as c2s from "./c2s/index.ts";
import * as s2c from "./s2c/index.ts";

/** A c2s module: reads an inbound packet and acts on it. */
export type Handler = (reader: Reader, session: Session) => void | Promise<void>;

/** An s2c module: builds an outbound packet from its own opcode. */
export type Builder = (op: number, ...args: never[]) => Packet;

type Outbound = typeof s2c;

/** Names we can send, and the arguments each takes after its injected opcode. */
export type OutboundName = keyof Outbound & string;

export type OutboundArgs<N extends OutboundName> = Outbound[N] extends (
  op: number,
  ...args: infer A
) => Packet
  ? A
  : never;

const OPS = new URL("./", import.meta.url).pathname;

function filesIn(dir: "c2s" | "s2c"): Set<string> {
  return new Set(
    [...new Glob("*.ts").scanSync({ cwd: `${OPS}${dir}` })]
      .filter((file) => file !== "index.ts")
      .map((file) => file.slice(0, -3)),
  );
}

export class Registry {
  readonly #handlers = new Map<number, Handler>();
  readonly #builders = new Map<string, { op: number; build: Builder }>();

  static load(): Registry {
    const registry = new Registry();

    for (const [dir, modules] of [
      ["c2s", c2s],
      ["s2c", s2c],
    ] as const) {
      // The generated index and the directory must agree; `bun run sync` fixes
      // any mismatch, and the tests fail if someone forgets to run it.
      const onDisk = filesIn(dir);
      const listed = new Set(Object.keys(modules));
      for (const name of onDisk) {
        if (!listed.has(name)) {
          throw new Error(`src/ops/${dir}/${name}.ts is missing from index.ts — run \`bun run sync\``);
        }
      }
      for (const name of listed) {
        if (!onDisk.has(name)) {
          throw new Error(`src/ops/${dir}/index.ts lists ${name}, which has no module`);
        }
      }

      for (const [name, fn] of Object.entries(modules)) {
        const op = opcodeFor(name); // throws if the filename is not a real opcode
        if (dir === "c2s") registry.#handlers.set(op, fn as Handler);
        else registry.#builders.set(name, { op, build: fn as Builder });
      }
    }
    return registry;
  }

  handlerFor(opcode: number): Handler | undefined {
    return this.#handlers.get(opcode);
  }

  build<N extends OutboundName>(name: N, ...args: OutboundArgs<N>): Packet {
    const entry = this.#builders.get(name);
    if (!entry) throw new Error(`no module in src/ops/s2c/ for ${name}`);
    return (entry.build as (op: number, ...rest: unknown[]) => Packet)(entry.op, ...args);
  }

  get summary(): string {
    const inbound = [...this.#handlers.keys()].map(opcodeName).sort();
    const outbound = [...this.#builders.keys()].sort();
    return `c2s ${inbound.length} (${inbound.join(", ")}), s2c ${outbound.length} (${outbound.join(", ")})`;
  }
}
