/**
 * Packet registry, keyed by filename and split by direction.
 *
 *   src/ops/c2s/GL_LOGIN_REQ.ts   the client sends it; we read and handle it
 *   src/ops/s2c/GL_LOGIN_ACK.ts   we send it; we build it
 *
 * The opcode name appears in the filename and nowhere inside the module. A
 * builder's first parameter is its own opcode, injected here, so the module
 * never has to name or import a constant.
 *
 * Direction comes from the folder, not the `_REQ`/`_ACK` suffix. Those
 * suffixes describe the *client's* view and do not always match ours:
 * `GT_PING_ACK` is an `_ACK` the server sends, and `GT_PING_REQ` is a `_REQ`
 * it receives (docs/PACKETS.md §3.15pre).
 *
 * The two `index.ts` files are generated by `bun run sync`, and both this
 * module and a test check they match the directory. They exist because ES
 * modules have no glob import and a dynamic `import(`./${name}.ts`)` degrades
 * to `any`, which would put opcode names and builder arguments back to failing
 * at runtime.
 */

import { Glob } from "bun";
import type { Packet, Reader } from "../packet.ts";
import { opcodeFor, opcodeName } from "../opcodes.ts";
import type { Connection } from "../connection.ts";
import * as c2s from "./c2s/index.ts";
import * as s2c from "./s2c/index.ts";

/** A c2s module: reads an inbound packet and handles it, start to finish. */
export type Handler = (reader: Reader, connection: Connection) => void | Promise<void>;

/** Names we can send, and the arguments each takes after its injected opcode. */
export type OutboundName = keyof typeof s2c & string;

export type OutboundArgs<N extends OutboundName> = (typeof s2c)[N] extends (
  op: number,
  ...args: infer A
) => Packet
  ? A
  : never;

function namesOnDisk(dir: "c2s" | "s2c"): string[] {
  const folder = new URL(`./${dir}/`, import.meta.url).pathname;
  return [...new Glob("*.ts").scanSync({ cwd: folder })]
    .filter((file) => file !== "index.ts")
    .map((file) => file.slice(0, -3));
}

/** Fail loudly if a module was added without regenerating the index. */
function checkInSync(dir: "c2s" | "s2c", modules: Record<string, unknown>): void {
  const listed = Object.keys(modules);
  const onDisk = namesOnDisk(dir);
  const missing = onDisk.filter((name) => !listed.includes(name));
  const extra = listed.filter((name) => !onDisk.includes(name));
  if (missing.length) {
    throw new Error(`src/ops/${dir}/: ${missing.join(", ")} not in index.ts — run \`bun run sync\``);
  }
  if (extra.length) {
    throw new Error(`src/ops/${dir}/index.ts lists ${extra.join(", ")}, which have no module`);
  }

  // Each module's function is named after its opcode, so the name shows up in
  // stack traces and when reading the file itself. That repeats the filename,
  // which is only safe because a mismatch is caught right here.
  for (const [name, fn] of Object.entries(modules)) {
    const actual = (fn as { name?: string }).name ?? "";
    if (actual !== name && actual !== `${name}_default`) {
      throw new Error(`src/ops/${dir}/${name}.ts exports a function named ${actual || "(anonymous)"}`);
    }
  }
}

checkInSync("c2s", c2s);
checkInSync("s2c", s2c);

/** opcode -> the module that handles it. */
const handlers = new Map<number, Handler>(
  Object.entries(c2s).map(([name, fn]) => [opcodeFor(name), fn as Handler]),
);

/** name -> its opcode, so builders can be called by name and stay typed. */
const opcodes = new Map<string, number>(
  Object.keys(s2c).map((name) => [name, opcodeFor(name)]),
);

export function handlerFor(opcode: number): Handler | undefined {
  return handlers.get(opcode);
}

export function build<N extends OutboundName>(name: N, ...args: OutboundArgs<N>): Packet {
  // The public signature keeps each builder's own argument list; internally the
  // union of builders has no common call signature, hence the widening.
  const builder = s2c[name] as unknown as (op: number, ...rest: unknown[]) => Packet;
  return builder(opcodes.get(name)!, ...args);
}

/** One line for the startup log. */
export function summary(): string {
  const inbound = [...handlers.keys()].map(opcodeName).sort();
  const outbound = [...opcodes.keys()].sort();
  return `c2s ${inbound.length} (${inbound.join(", ")}), s2c ${outbound.length} (${outbound.join(", ")})`;
}
