#!/usr/bin/env bun
/**
 * Regenerate `src/ops/{c2s,s2c}/index.ts` from the files in those folders.
 *
 * ES modules have no glob import, and a dynamic `import(`./${name}.ts`)` with a
 * non-literal name degrades to `any` — which would put opcode names and
 * builder arguments back to failing at runtime. So a static list is required.
 * It is generated rather than hand-written, and `test/ops.test.ts` fails if
 * it is stale, so it can never disagree with the directory.
 *
 *   bun run sync
 */

import { Glob } from "bun";

const OPS = new URL("../src/ops/", import.meta.url).pathname;

const HEADER = (dir: "c2s" | "s2c") =>
  `// Generated by \`bun run sync\`. Do not edit by hand.
//
// ${
    dir === "c2s"
      ? "Packets the client sends us. Each module reads one and acts on it."
      : "Packets we send the client. Each module builds one from its own opcode."
  }
`;

let changed = false;

for (const dir of ["c2s", "s2c"] as const) {
  const names = [...new Glob("*.ts").scanSync({ cwd: `${OPS}${dir}` })]
    .filter((file) => file !== "index.ts")
    .map((file) => file.slice(0, -3))
    .sort();

  const body =
    `${HEADER(dir)}\n` +
    names.map((name) => `export { default as ${name} } from "./${name}.ts";`).join("\n") +
    "\n";

  const path = `${OPS}${dir}/index.ts`;
  const existing = await Bun.file(path)
    .text()
    .catch(() => "");

  if (existing !== body) {
    await Bun.write(path, body);
    changed = true;
    console.log(`wrote src/ops/${dir}/index.ts (${names.length} modules)`);
  } else {
    console.log(`src/ops/${dir}/index.ts is up to date (${names.length} modules)`);
  }
}

if (changed) console.log("\nrun `bun test` to confirm");
